from __future__ import absolute_import
from django import forms
from apps.datoslaborales.models import datoslaborales

class datoslaboralesform(forms.ModelForm):
    class Meta:
        model = datoslaborales
        fields = [
        'nombre',
        'rfc',
        'curp',

        'calle_numero',
        'colonia',
        'delegacion',
        'codigo_pos',
        'entidad',
        'telefono_part',
        'telefono_cel',
        'correo_per',
        'escolaridad',
        'nombre_lin_ce_afin',
        'numero_cedula',
        'nombre_lin_ce_noafin',
        'numero_cedula_noafin',
        'clinica',
        'banco',

        'funcion',
        'clave_presupuestal',
        'motivo',
        'adscrip',
        'escuela',
        'clave_eco',
        'cct',
        'zona_esco',
        'cct_cobro',
        'horas_cct',
        'efecto_desde',
        'efecto_hasta',
        'ingre_sep',
        'ingre_gob',
        'obtubo_plaza',
        'proceso_evaluacion',
        'nivel_carrera',
        'sdpc',

        'adscrip_adi',
        'escuela_adi',
        'clave_eco_adi',
        'cct_adi',
        'zona_esco_adi',
        'cct_cobro_adi',
        'clave_presupuestal_adi',
        'expe_docente',
        'expe_sinfunciones',
        ]

        labels = {
        'nombre': 'Nombre',
        'rfc': 'RFC',
        'curp': 'CURP',

        'calle_numero':'Calle y numero',
        'colonia': 'Colonia',
        'delegacion': 'Delegacion',
        'codigo_pos':'Codigo Postal',
        'entidad': 'Entidad',
        'telefono_part': 'Telefono Particular',
        'telefono_cel': 'Telefono Celular',
        'correo_per':'Correo Personal',
        'escolaridad':'Escolaridad',
        'nombre_lin_ce_afin':'Nombre de la Licenciatura con Cedula Profesional (Afin a la Educacion)',
        'numero_cedula':'Numero de Cedula Profesional',
        'nombre_lin_ce_noafin': 'Nombre de la Licenciatura no Afin a la Educacion (con Cedula)',
        'numero_cedula_noafin':'Numero de Cedula Profesional',
        'clinica':'Clinica Medico Familiar del ISSSTE que le Corresponde',
        'banco':'Institucion Bancaria de Deposito de Nomina',

        'funcion':'Funcion',
        'clave_presupuestal':'Clave Presupuestal',
        'motivo': 'Motivo',
        'adscrip': 'Adscipcion al C.C.T',
        'escuela': 'Escuela',
        'clave_eco': 'Clave economica',
        'cct': 'C.C.T',
        'zona_esco':'Zona Escolar',
        'cct_cobro':'C.C.T de Cobro',
        'horas_cct':'Horas en el C.C.T',
        'efecto_desde':'Desde',
        'efecto_hasta':'Hasta',
        'ingre_sep':'Ing. a la SEP. (dd/mm/aaaa)',
        'ingre_gob':'Ing. GOB. FED. (dd/mm/aaaa)',
        'obtubo_plaza': 'Proceso por el Cual Obtuvo la Plaza',
        'proceso_evaluacion':'Participacion en Procesos de Evaluacion',
        'nivel_carrera':'Nivel de Carrera Magisterial',
        'sdpc':'Nivel de SDPC',

        'adscrip_adi':'Adscripcion en la Plaza Adicional (Nombre de la Escuela, CCT, Clave Economica, Numero de Horas)',
        'escuela_adi':'Escuela',
        'clave_eco_adi':'Clave Economica',
        'cct_adi':'C.C.T',
        'zona_esco_adi':'Zona Escolar',
        'cct_cobro_adi':'C.C.T donde Cobra',
        'clave_presupuestal_adi':'Clave Prosupuestal',
        'expe_docente':'Experiencia Como Docente Frente a Grupo',
        'expe_sinfunciones':'Experiencia sin Funciones Frente a Grupo',
        }
