# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datoslaborales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=25)),
                ('curp', models.CharField(max_length=25)),
                ('calle_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('delegacion', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_pos', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_part', models.CharField(blank=True, max_length=25, null=True)),
                ('telefono_cel', models.CharField(blank=True, max_length=25, null=True)),
                ('correo_per', models.EmailField(blank=True, max_length=254, null=True)),
                ('escolaridad', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_lin_ce_afin', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cedula', models.CharField(blank=True, max_length=25, null=True)),
                ('nombre_lin_ce_noafin', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cedula_noafin', models.CharField(blank=True, max_length=25, null=True)),
                ('clinica', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('funcion', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_presupuestal', models.CharField(blank=True, max_length=27, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('adscrip', models.CharField(blank=True, max_length=100, null=True)),
                ('escuela', models.CharField(blank=True, max_length=100, null=True)),
                ('clave_eco', models.CharField(blank=True, max_length=50, null=True)),
                ('cct', models.CharField(blank=True, max_length=100, null=True)),
                ('zona_esco', models.CharField(blank=True, max_length=50, null=True)),
                ('cct_cobro', models.CharField(blank=True, max_length=100, null=True)),
                ('horas_cct', models.CharField(blank=True, max_length=25, null=True)),
                ('efecto_desde', models.CharField(blank=True, max_length=100, null=True)),
                ('efecto_hasta', models.CharField(blank=True, max_length=100, null=True)),
                ('ingre_sep', models.CharField(blank=True, max_length=100, null=True)),
                ('ingre_gob', models.CharField(blank=True, max_length=100, null=True)),
                ('obtubo_plaza', models.CharField(blank=True, max_length=100, null=True)),
                ('proceso_evaluacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_carrera', models.CharField(blank=True, max_length=10, null=True)),
                ('sdpc', models.CharField(blank=True, max_length=50, null=True)),
                ('adscrip_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('escuela_adi', models.CharField(blank=True, max_length=100)),
                ('clave_eco_adi', models.CharField(blank=True, max_length=100)),
                ('cct_adi', models.CharField(blank=True, max_length=100)),
                ('zona_esco_adi', models.CharField(blank=True, max_length=25)),
                ('cct_cobro_adi', models.CharField(blank=True, max_length=100)),
                ('clave_presupuestal_adi', models.CharField(blank=True, max_length=30)),
                ('expe_docente', models.CharField(blank=True, max_length=10, null=True)),
                ('expe_sinfunciones', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
