from __future__ import absolute_import
from django import forms
from apps.centro.models import CentroTrabajo

class centroform(forms.ModelForm):
    class Meta:
        model = CentroTrabajo

        fields = [
        'ciclo_escolar',

        'Nombre_Centro',
        'telefono',
        'centro_trabajo',
        'direccion_operativa',
        'clave_economica',
        'n_zona',
        'domicilio_intitucional',
        'nombre_responsable',
        'correo_intitucional',
        'mat',
        'vesp',
        'j_a',
        't_c',
        'eps',
        'noct',
        'zona',
        'dictaminado',
        'encargado',
        'promocion',

        'grupo_pri',
        'grupo_seg',
        'grupo_ter',
        'grupo_cua',
        'grupo_qui',
        'grupo_sex',
        'grupo_nueve_catorse',
        'grupo_tot',

        'matri_pri',
        'matri_seg',
        'matri_ter',
        'matri_cua',
        'matri_qui',
        'matri_sex',
        'matri_nueve_catorse',
        'matri_tot',

        'doce_pri',
        'doce_seg',
        'doce_ter',
        'doce_cua',
        'doce_qui',
        'doce_sex',
        'doce_nueve_catorse',
        'doce_tot',

        'Supervisor_Mat',
        'Supervisor_Vep',
        'Supervisor_Dis',
        'Supervisor_Otr',
        'Supervisor_Tot',

        'Supervisor_E_F_Mat',
        'Supervisor_E_F_Vep',
        'Supervisor_E_F_Dis',
        'Supervisor_E_F_Otr',
        'Supervisor_E_F_Tot',


        'APT_Mate_Dic_Mat',
        'APT_Mate_Dic_Vep',
        'APT_Mate_Dic_Dis',
        'APT_Mate_Dic_Otr',
        'APT_Mate_Dic_Tot',

        'APT_LOE_Mat',
        'APT_LOE_Vep',
        'APT_LOE_Dis',
        'APT_LOE_Otr',
        'APT_LOE_Tot',

        'Director_Mat',
        'Director_Vep',
        'Director_Dis',
        'Director_Otr',
        'Director_Tot',

        'Director_OTN_Mat',
        'Director_OTN_Vep',
        'Director_OTN_Dis',
        'Director_OTN_Otr',
        'Director_OTN_Tot',

        'Docente_Mat',
        'Docente_Vep',
        'Docente_Dis',
        'Docente_Otr',
        'Docente_Tot',

        'Docente_C_A_Mat',
        'Docente_C_A_Vep',
        'Docente_C_A_Dis',
        'Docente_C_A_Otr',
        'Docente_C_A_Tot',

        'Docente_OTN_Mat',
        'Docente_OTN_Vep',
        'Docente_OTN_Dis',
        'Docente_OTN_Otr',
        'Docente_OTN_Tot',

        'Docente_E_F_Mat',
        'Docente_E_F_Vep',
        'Docente_E_F_Dis',
        'Docente_E_F_Otr',
        'Docente_E_F_Tot',

        'Docente_E_F_C_A_Mat',
        'Docente_E_F_C_A_Vep',
        'Docente_E_F_C_A_Dis',
        'Docente_E_F_C_A_Otr',
        'Docente_E_F_C_A_Tot',

        'ASP_Mat',
        'ASP_Vep',
        'ASP_Dis',
        'ASP_Otr',
        'ASP_Tot',

        'administrativo_Mat',
        'administrativo_Vep',
        'administrativo_Dis',
        'administrativo_Otr',
        'administrativo_Tot',
        'total',

        'director',
        'docentes_frente_grupo',
        'sub_gestion',
        'sub_aca',
        'maes_tall',
        'Promotor_tic_e0280',
        'Promotor_tic_horas',
        'docentes_sin_grupo',
        'docentes_cambio_actividad',
        'Docente_OTN',
        'total1',

        'Conserje',
        'Conserje_C_A',
        'Asis_ser_plan',
        'Asis_ser_plan_C_A',
        'Asis_ser_plan_OTN',
        'total2',

        'administrativo',

        'docentes_edu_fis',
        'docentes_edu_fis_C_A',
        'docentes_ingles',
        'docentes_ingles_C_A',
        'docentes_edu_art',
        'docentes_musica',
        'total3',

        'fecha_elaboracion',
        ]
        labels = {
        'ciclo_escolar': 'Ciclo Escolar',
        'Nombre_Centro': 'Nommbre del Centro de Trabajo',
        'telefono': 'telefono',
        'centro_trabajo':'Centro de Trabajo',
        'direccion_operativa': 'Direecion Operativa',
        'clave_economica': 'Clave Economica',
        'n_zona': 'N de Zona',
        'domicilio_intitucional': 'Domicilio Institucional',
        'nombre_responsable': 'Nombre del Responsable',
        'correo_intitucional': 'Correo Institucional',
        'mat': 'MAT',
        'vesp': 'VESP',
        'j_a': 'J.A.',
        't_c': 'T.C.',
        'eps': 'EPS',
        'noct': 'NOCT',
        'zona': 'Zona',
        'dictaminado': 'Dcintaminado',
        'encargado': 'Encargado',
        'promocion': 'Promocion',

        'grupo_pri':'Primero',
        'grupo_seg':'Segundo',
        'grupo_ter':'Tercero',
        'grupo_cua':'Cuarto',
        'grupo_qui':'Quinto',
        'grupo_sex':'Sexto',
        'grupo_9_14':'9/14',
        'grupo_tot':'Total',

        'Supervisor_Mat':'Mat',
        'Supervisor_Vep':'Vep',
        'Supervisor_Dis':'Dis',
        'Supervisor_Otr':'Otr',
        'Supervisor_Tot':'Tot',

        'Supervisor_E_F_Mat':'Mat',
        'Supervisor_E_F_Vep':'Vep',
        'Supervisor_E_F_Dis':'Dis',
        'Supervisor_E_F_Otr':'Otr',
        'Supervisor_E_F_Tot':'Tot',

        'APT_Mate_Dic_Mat':'Mat',
        'APT_Mate_Dic_Vep':'Vep',
        'APT_Mate_Dic_Dis':'Dis',
        'APT_Mate_Dic_Otr':'Otr',
        'APT_Mate_Dic_Tot':'Tot',

        'APT_LOE_Mat':'Mat',
        'APT_LOE_Vep':'Vep',
        'APT_LOE_Dis':'Dis',
        'APT_LOE_Otr':'Otr',
        'APT_LOE_Tot':'Tot',

        'Director_Mat':'Mat',
        'Director_Vep':'Vep',
        'Director_Dis':'Dis',
        'Director_Otr':'Otr',
        'Director_Tot':'Tot',

        'Director_OTN_Mat':'Mat',
        'Director_OTN_Vep':'Vep',
        'Director_OTN_Dis':'Dis',
        'Director_OTN_Otr':'Otr',
        'Director_OTN_Tot':'Tot',

        'Docente_Mat':'Mat',
        'Docente_Vep':'Vep',
        'Docente_Dis':'Dis',
        'Docente_Otr':'Otr',
        'Docente_Tot':'Tot',

        'Docente_C_A_Mat':'Mat',
        'Docente_C_A_Vep':'Vep',
        'Docente_C_A_Dis':'Dis',
        'Docente_C_A_Otr':'Otr',
        'Docente_C_A_Tot':'Tot',

        'Docente_OTN_Mat':'Mat',
        'Docente_OTN_Vep':'Vep',
        'Docente_OTN_Dis':'Dis',
        'Docente_OTN_Otr':'Otr',
        'Docente_OTN_Tot':'Tot',

        'Docente_E_F_Mat':'Mat',
        'Docente_E_F_Vep':'Vep',
        'Docente_E_F_Dis':'Dis',
        'Docente_E_F_Otr':'Otr',
        'Docente_E_F_Tot':'Tot',

        'Docente_E_F_C_A_Mat':'Mat',
        'Docente_E_F_C_A_Vep':'Vep',
        'Docente_E_F_C_A_Dis':'Dis',
        'Docente_E_F_C_A_Otr':'Otr',
        'Docente_E_F_C_A_Tot':'Tot',

        'ASP_Mat':'Mat',
        'ASP_Vep':'Vep',
        'ASP_Dis':'Dis',
        'ASP_Otr':'Otr',
        'ASP_Tot':'Tot',

        'administrativo_Mat':'Mat',
        'administrativo_Vep':'Vep',
        'administrativo_Dis':'Dis',
        'administrativo_Otr':'Otr',
        'administrativo_Tot':'Tot',
        'total':'Total',

        'director':'Director (a)',
        'docentes_frente_grupo':'Docentes Frente a Grupo',
        'sub_gestion':'Subdirector de Gestion Escolar',
        'sub_aca':'Subdirector Academico',
        'maes_tall':'Maestro de Taller de Lectura y Escritura',
        'Promotor_tic_e0280':'Promotor de TIC (E0280)',
        'Promotor_tic_horas':'Promotor de TIC (Clave de  horas)',
        'docentes_sin_grupo':'Docente sin grupo',
        'docentes_cambio_actividad':' Docente con Cambio de Actividad',
        'Docente_OTN':' Docente OTN',
        'total1':'Total',

        'Conserje':'Conserje',
        ',Conserje_C_A':'Conserje C/A',
        'Asis_ser_plan':'Asistente de Servicios en Plantel',
        'Asis_ser_plan_C_A':'Asistente de Servicios en Plantel C/A',
        'Asis_ser_plan_OTN':'Asistente de Servicios en Plantel OTN',
        'total2':'Total',

        'administrativo':'Administrativo',

        'docentes_edu_fis':'Docente (s) de Educacion Fisica',
        'docentes_edu_fis_C_A':'Docente (s) de Educacion Fisica C/A',
        'docentes_ingles':'Docente (s) de Ingles',
        'docentes_ingles_C_A':'Docente (s) de Ingles',
        'docentes_edu_art':'Docente (s) de Educacion Artistica',
        'docentes_musica':'Docente(s) Musica',
        'total3':'Total',

        'fecha_elaboracion':'Fecha de elaboracion',
        }
