from __future__ import absolute_import

from django.db import models

class CentroTrabajo(models.Model):
    ciclo_escolar = models.CharField(max_length=10)
    Nombre_Centro = models.CharField(max_length=50)
    telefono = models.CharField(max_length=50)
    centro_trabajo = models.CharField(max_length=15)
    direccion_operativa = models.IntegerField()
    clave_economica = models.CharField(max_length=20)
    n_zona = models.IntegerField()
    domicilio_intitucional = models.CharField(max_length=100)
    nombre_responsable = models.CharField(max_length=50)
    correo_intitucional = models.EmailField()
    mat = models.BooleanField()
    vesp = models.BooleanField()
    j_a = models.BooleanField()
    t_c = models.BooleanField()
    eps = models.BooleanField()
    noct = models.BooleanField()
    zona = models.BooleanField()
    dictaminado = models.BooleanField()
    encargado = models.BooleanField()
    promocion = models.BooleanField()
    grupo_pri = models.IntegerField()
    grupo_seg = models.IntegerField()
    grupo_ter = models.IntegerField()
    grupo_cua = models.IntegerField()
    grupo_qui = models.IntegerField()
    grupo_sex = models.IntegerField()
    grupo_nueve_catorse = models.IntegerField(null=True, blank=True)
    grupo_tot = models.IntegerField()
    matri_pri = models.IntegerField(null=True, blank=True)
    matri_seg = models.IntegerField(null=True, blank=True)
    matri_ter = models.IntegerField(null=True, blank=True)
    matri_cua = models.IntegerField(null=True, blank=True)
    matri_qui = models.IntegerField(null=True, blank=True)
    matri_sex = models.IntegerField(null=True, blank=True)
    matri_nueve_catorse = models.IntegerField(null=True, blank=True)
    matri_tot = models.IntegerField(null=True, blank=True)
    doce_pri = models.IntegerField(null=True, blank=True)
    doce_seg = models.IntegerField(null=True, blank=True)
    doce_ter = models.IntegerField(null=True, blank=True)
    doce_cua = models.IntegerField(null=True, blank=True)
    doce_qui = models.IntegerField(null=True, blank=True)
    doce_sex = models.IntegerField(null=True, blank=True)
    doce_nueve_catorse = models.IntegerField(null=True, blank=True)
    doce_tot = models.IntegerField(null=True, blank=True)
    Supervisor_Mat = models.IntegerField(null=True, blank=True)
    Supervisor_Vep = models.IntegerField(null=True, blank=True)
    Supervisor_Dis = models.IntegerField(null=True, blank=True)
    Supervisor_Otr = models.IntegerField(null=True, blank=True)
    Supervisor_Tot = models.IntegerField(null=True, blank=True)
    Supervisor_E_F_Mat = models.IntegerField(null=True, blank=True)
    Supervisor_E_F_Vep = models.IntegerField(null=True, blank=True)
    Supervisor_E_F_Dis = models.IntegerField(null=True, blank=True)
    Supervisor_E_F_Otr = models.IntegerField(null=True, blank=True)
    Supervisor_E_F_Tot = models.IntegerField(null=True, blank=True)
    APT_Mate_Dic_Mat = models.IntegerField(null=True, blank=True)
    APT_Mate_Dic_Vep = models.IntegerField(null=True, blank=True)
    APT_Mate_Dic_Dis = models.IntegerField(null=True, blank=True)
    APT_Mate_Dic_Otr = models.IntegerField(null=True, blank=True)
    APT_Mate_Dic_Tot = models.IntegerField(null=True, blank=True)
    APT_LOE_Mat = models.IntegerField(null=True, blank=True)
    APT_LOE_Vep = models.IntegerField(null=True, blank=True)
    APT_LOE_Dis = models.IntegerField(null=True, blank=True)
    APT_LOE_Otr = models.IntegerField(null=True, blank=True)
    APT_LOE_Tot = models.IntegerField(null=True, blank=True)
    Director_Mat = models.IntegerField(null=True, blank=True)
    Director_Vep = models.IntegerField(null=True, blank=True)
    Director_Dis = models.IntegerField(null=True, blank=True)
    Director_Otr = models.IntegerField(null=True, blank=True)
    Director_Tot = models.IntegerField(null=True, blank=True)
    Director_OTN_Mat = models.IntegerField(null=True, blank=True)
    Director_OTN_Vep = models.IntegerField(null=True, blank=True)
    Director_OTN_Dis = models.IntegerField(null=True, blank=True)
    Director_OTN_Otr = models.IntegerField(null=True, blank=True)
    Director_OTN_Tot = models.IntegerField(null=True, blank=True)
    Docente_Mat = models.IntegerField(null=True, blank=True)
    Docente_Vep = models.IntegerField(null=True, blank=True)
    Docente_Dis = models.IntegerField(null=True, blank=True)
    Docente_Otr = models.IntegerField(null=True, blank=True)
    Docente_Tot = models.IntegerField(null=True, blank=True)
    Docente_C_A_Mat = models.IntegerField(null=True, blank=True)
    Docente_C_A_Vep = models.IntegerField(null=True, blank=True)
    Docente_C_A_Dis = models.IntegerField(null=True, blank=True)
    Docente_C_A_Otr = models.IntegerField(null=True, blank=True)
    Docente_C_A_Tot = models.IntegerField(null=True, blank=True)
    Docente_OTN_Mat = models.IntegerField(null=True, blank=True)
    Docente_OTN_Vep = models.IntegerField(null=True, blank=True)
    Docente_OTN_Dis = models.IntegerField(null=True, blank=True)
    Docente_OTN_Otr = models.IntegerField(null=True, blank=True)
    Docente_OTN_Tot = models.IntegerField(null=True, blank=True)
    Docente_E_F_Mat = models.IntegerField(null=True, blank=True)
    Docente_E_F_Vep = models.IntegerField(null=True, blank=True)
    Docente_E_F_Dis = models.IntegerField(null=True, blank=True)
    Docente_E_F_Otr = models.IntegerField(null=True, blank=True)
    Docente_E_F_Tot = models.IntegerField(null=True, blank=True)
    Docente_E_F_C_A_Mat = models.IntegerField(null=True, blank=True)
    Docente_E_F_C_A_Vep = models.IntegerField(null=True, blank=True)
    Docente_E_F_C_A_Dis = models.IntegerField(null=True, blank=True)
    Docente_E_F_C_A_Otr = models.IntegerField(null=True, blank=True)
    Docente_E_F_C_A_Tot = models.IntegerField(null=True, blank=True)
    ASP_Mat = models.IntegerField(null=True, blank=True)
    ASP_Vep = models.IntegerField(null=True, blank=True)
    ASP_Dis = models.IntegerField(null=True, blank=True)
    ASP_Otr = models.IntegerField(null=True, blank=True)
    ASP_Tot = models.IntegerField(null=True, blank=True)
    administrativo_Mat = models.IntegerField(null=True, blank=True)
    administrativo_Vep = models.IntegerField(null=True, blank=True)
    administrativo_Dis = models.IntegerField(null=True, blank=True)
    administrativo_Otr = models.IntegerField(null=True, blank=True)
    administrativo_Tot = models.IntegerField(null=True, blank=True)
    total = models.IntegerField(null=True, blank=True)
    director = models.IntegerField(null=True, blank=True)
    docentes_frente_grupo = models.IntegerField(null=True, blank=True)
    sub_gestion = models.IntegerField(null=True, blank=True)
    sub_aca = models.IntegerField(null=True, blank=True)
    maes_tall = models.IntegerField(null=True, blank=True)
    Promotor_tic_e0280 = models.IntegerField(null=True, blank=True)
    Promotor_tic_horas = models.IntegerField(null=True, blank=True)
    docentes_sin_grupo = models.IntegerField(null=True, blank=True)
    docentes_cambio_actividad = models.IntegerField(null=True, blank=True)
    Docente_OTN = models.IntegerField(null=True, blank=True)
    total1 = models.IntegerField(null=True, blank=True)
    Conserje = models.IntegerField(null=True, blank=True)
    Conserje_C_A = models.IntegerField(null=True, blank=True)
    Asis_ser_plan = models.IntegerField(null=True, blank=True)
    Asis_ser_plan_C_A = models.IntegerField(null=True, blank=True)
    Asis_ser_plan_OTN = models.IntegerField(null=True, blank=True)
    total2 = models.IntegerField(null=True, blank=True)
    administrativo = models.IntegerField(null=True, blank=True)
    docentes_edu_fis = models.IntegerField(null=True, blank=True)
    docentes_edu_fis_C_A = models.IntegerField(null=True, blank=True)
    docentes_ingles = models.IntegerField(null=True, blank=True)
    docentes_ingles_C_A = models.IntegerField(null=True, blank=True)
    docentes_edu_art = models.IntegerField(null=True, blank=True)
    docentes_musica = models.IntegerField(null=True, blank=True)
    total3 = models.IntegerField(null=True, blank=True)
    fecha_elaboracion = models.DateField()
    def __unicode__(self):
        return self.Nombre_Centro
